version: "3.2"
services:
  api:
    user: ${UID}:${GID}
    image: flask_api
    container_name: ml_api
    build:
      args:
        - UID=${UID}
        - GID=${GID}
      context: ./api
      target: build
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - WORKER_TIMEOUT=120
    depends_on:
      - redis
      - model

    volumes:
      - ./api:/src # Mount the local 'api' directory into the '/src' directory in the container
      - ./feedback:/src/feedback
      - ./uploads:/src/static/uploads
    networks:
      - my_network  # Connect this service to the custom network

  redis:
    image: redis:6.2.6
    networks:
      - my_network  # Connect this service to the custom network

  model:
    user: ${UID}:${GID}
    image: ml_service
    build:
      args:
        - UID=${UID}
        - GID=${GID}
      context: ./model
      target: build
    depends_on:
      - redis
    volumes:
      - ./model:/src # Mount the local 'model' directory into the '/src' directory in the container
      - ./uploads:/src/uploads
    networks:
      - my_network  # Connect this service to the custom network

networks:
  my_network:
    driver: bridge